name: sistema_ventas_adaptativo
description: Sistema de ventas adaptativo basado en contexto y expresiones faciales.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.9.2
  image_picker: ^1.1.2
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
